# Used to test password effectively set. Default policy provided by
# image allows paswordless local connections (trust).
# Temporarly use this config:
# - /tmp/pg_hba.conf inside container
# - execute ./hba_apply.sql
# - restart container to propagate 'hba_file' value server-side
# - script, tests
# - execute ./hba_reset.sql for shipped defaults
# - restart container


local   all             hr_user                         scram-sha-256
host    all             hr_user         127.0.0.1/32    scram-sha-256
host    all             hr_user         ::1/128         scram-sha-256

# defaults
local   all             all                             trust
host    all             all             127.0.0.1/32    trust
host    all             all             ::1/128         trust

local   replication     all                             trust
host    replication     all             127.0.0.1/32    trust
host    replication     all             ::1/128         trust

host all all all scram-sha-256
